inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-rake

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - '**/*.gemspec'
    - '**/Rakefile'
